### ISSUE TITLE
error LNK2001: unresolved external symbol

### ISSUE THREAD

**Issue by manuloku** [okk3/OpenGL-ES-SDK#1]
Hey! I'm trying a lot to compile OTClient with the SDK, btw it's returning this errors in console:

`1>     Creating library C:\otclient-master\vc14\../otclient.lib and object C:\otclient-master\vc14\../otclient.exp
1>mapview.obj : error LNK2001: unresolved external symbol __imp__glUniform1f@8
1>mapview.obj : error LNK2001: unresolved external symbol __imp__glUniform2f@12
1>coordsbuffer.obj : error LNK2001: unresolved external symbol __imp__glBindBuffer@8
1>coordsbuffer.obj : error LNK2001: unresolved external symbol __imp__glBufferData@16
1>framebuffer.obj : error LNK2001: unresolved external symbol __imp__glCheckFramebufferStatus@4
1>framebuffer.obj : error LNK2001: unresolved external symbol __imp__glGenFramebuffers@8
1>framebuffer.obj : error LNK2001: unresolved external symbol __imp__glFramebufferTexture2D@20
1>framebuffer.obj : error LNK2001: unresolved external symbol __imp__glBindFramebuffer@8
1>framebuffer.obj : error LNK2001: unresolved external symbol __imp__glDeleteFramebuffers@8
1>hardwarebuffer.obj : error LNK2001: unresolved external symbol __imp__glDeleteBuffers@8
1>hardwarebuffer.obj : error LNK2001: unresolved external symbol __imp__glGenBuffers@8
1>paintershaderprogram.obj : error LNK2001: unresolved external symbol __imp__glUniform1i@8
1>paintershaderprogram.obj : error LNK2001: unresolved external symbol __imp__glUniform4f@20
1>paintershaderprogram.obj : error LNK2001: unresolved external symbol __imp__glActiveTexture@4
1>paintershaderprogram.obj : error LNK2001: unresolved external symbol __imp__glUniformMatrix3fv@16

1>shader.obj : error LNK2001: unresolved external symbol __imp__glShaderSource@16
1>shader.obj : error LNK2001: unresolved external symbol __imp__glDeleteShader@4
1>shader.obj : error LNK2001: unresolved external symbol __imp__glGetShaderInfoLog@16
1>shader.obj : error LNK2001: unresolved external symbol __imp__glCompileShader@4
1>shader.obj : error LNK2001: unresolved external symbol __imp__glCreateShader@4
1>shader.obj : error LNK2001: unresolved external symbol __imp__glGetShaderiv@12
1>shaderprogram.obj : error LNK2001: unresolved external symbol __imp__glBindAttribLocation@12
1>shaderprogram.obj : error LNK2001: unresolved external symbol __imp__glGetAttribLocation@8
1>shaderprogram.obj : error LNK2001: unresolved external symbol __imp__glCreateProgram@0
1>shaderprogram.obj : error LNK2001: unresolved external symbol __imp__glGetProgramiv@12
1>shaderprogram.obj : error LNK2001: unresolved external symbol __imp__glLinkProgram@4
1>shaderprogram.obj : error LNK2001: unresolved external symbol __imp__glDetachShader@8
1>shaderprogram.obj : error LNK2001: unresolved external symbol __imp__glGetUniformLocation@8
1>shaderprogram.obj : error LNK2001: unresolved external symbol __imp__glAttachShader@8
1>shaderprogram.obj : error LNK2001: unresolved external symbol __imp__glUseProgram@4
1>shaderprogram.obj : error LNK2001: unresolved external symbol __imp__glDeleteProgram@4
1>texture.obj : error LNK2001: unresolved external symbol __imp__glGenerateMipmap@4
1>painterogl.obj : error LNK2001: unresolved external symbol __imp__glBlendEquation@4
1>painterogl.obj : error LNK2001: unresolved external symbol __imp__glBlendFuncSeparate@16
1>painterogl2.obj : error LNK2001: unresolved external symbol __imp__glVertexAttribPointer@24
1>painterogl2.obj : error LNK2001: unresolved external symbol __imp__glDisableVertexAttribArray@4
1>painterogl2.obj : error LNK2001: unresolved external symbol __imp__glEnableVertexAttribArray@4
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglGetConfigs@16
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglCreateContext@16
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglInitialize@12
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglChooseConfig@20
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglDestroySurface@8
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglGetDisplay@4
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglCreateWindowSurface@16
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglGetError@0
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglSwapInterval@8
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglTerminate@4
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglSwapBuffers@8
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglMakeCurrent@16
1>win32window.obj : error LNK2001: unresolved external symbol __imp__eglDestroyContext@8`

What am I doing wrong?

Sorry if it's a silly question, btw I'm really stuck here for long days and found nothing relationed, even not related to OTClient.

**Comment by okk3** [comment]
You haven't linked the correct libraries.

**Comment by lanister123** [comment]
I too have the same issue.

**Comment by okk3** [comment]
Hello everyone having this issue,

I added support for the newer Visual Studios, you can find an answer to these problems here:
https://github.com/okk3/OpenGL-ES-SDK/issues/2

Best Wishes
Okke

**Comment by okk3** [comment]
Closing until someone tests it.
