### ISSUE TITLE
Sample compiles but doesn't work in VS 2015/VS2017 - W10 - GTX1080 latest drivers

### ISSUE THREAD

**Issue by spekdrum** [okk3/OpenGL-ES-SDK#2]
I compiled the sample project but when I execute the program it fails at this line:

`eglDisplay = eglGetDisplay(nativeDisplay);`

The exception given (in spanish) is the following:
Excepción producida en 0x00000000 en GLESSample.exe: 0xC0000005: Infracción de acceso al ejecutar la ubicación 0x00000000.

which means: access violation.

Compiled in VS2015 and VS2017 with same results.

**Comment by okk3** [comment]
Hello @spekdrum 

Sorry for the very long not answered question:

I added support for newer MSVC, now you can just add under Properties > C++ > General > Additional Include Directories > Path to OpenGL-ES-SDK > include folder > (OpenGL-ES-SDK/include)
Under Linker > General > Additional Library Directories > (OpenGL-ES-SDK/lib)
Under Linker > Input > Additional Dependencies > add `libEGL.lib` and `libGLEsV2.lib`

Now to finalize just drop the both DLLs I added to the latest commit, should be inside DLL folder to your executables directory and run it.

Best Wishes
Okke

**Comment by okk3** [comment]
Closing until someone tests it.
